runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: common.routes.app
  secure: always

libraries:
- name: MySQLdb
  version: "latest"
- name: pycrypto
  version: "latest"

env_variables:
  CLOUDSQL_CONNECTION_NAME: socratiq-app:us-central1:socratiq
  CLOUDSQL_USER: root
  CLOUDSQL_DB: v3

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^venv$
- ^gae-lib/appdirs.*
- ^gae-lib/easy_install.*
- ^gae-lib/packaging.*
- ^gae-lib/pip.*
- ^gae-lib/pkg_resources.*
- ^gae-lib/pyparsing.*
- ^gae-lib/setuptools.*
- ^gae-lib/six.*
- ^gae-lib/venv.*
- ^gae-lib/webapp.*
- ^gae-lib/wheel.*
